### ISSUE TITLE
Don't reinvent the wheel for core R functions

### ISSUE THREAD

**Issue by sholderbach** [datascience-mobi/2021-topic-01-team-04#1]
As an example, this is a reimplementation of the `rev()` function provided in the base install of R:

https://github.com/datascience-mobi/2021-topic-01-team-04/blob/27d500ba52a09a8720f132c7ee2b386320cf86b5/DataCleanupTreatment.Rmd#L53-L60

This is actually really bad from a computational performance standpoint:

- those functions are typically internally written as compiled C++ and thus likely faster than any interpreted R you could write
- In this case, you allocate at first an empty vector and proceed by appending each element one at a time. This will cause a massive amount of internal reallocations as the new vector is created by copying the old elements and placing the new value. (There are ways in R to create a vector with known size and place the elements into it without causing this)

**Comment by Hrafnkloo** [comment]
Thank you, didn't check for such a function.
